# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountnum', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Accounttype',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ceiling', models.FloatField()),
                ('interest', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'accounttype',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('abbreviation', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transnum', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('transdate', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Phonenumber',
            fields=[
                ('customerid', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='banking_app.Customer')),
                ('phonenum', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
                'db_table': 'phonenumber',
            },
        ),
    ]
